# -*- coding: utf-8 -*-
"""app

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1cepViZFOzLF2rU-gi-IScg4GN_ZtOM1t
"""


import streamlit as st
from transformers import pipeline

st.title("Review Classifier - Model 2")

@st.cache_resource
def load_model():
    return pipeline("text-classification", model="cardiffnlp/twitter-roberta-base-sentiment-latest")

classifier = load_model()

user_input = st.text_area("Enter review text:", "Great service and delicious food!")

if st.button("Analyze"):
    if user_input.strip():
        result = classifier(user_input)[0]
        st.write(f"Result: {result['label']} (Score: {result['score']:.2f})")
    else:
        st.warning("Please enter some text.")

